### ISSUE TITLE
Generate trace gif?

### ISSUE THREAD

**Issue by Hellscaped** [Wunkolo/qHilbert#2]
I was looking for a way to generate a hilbert curve for a wallpaper, and I was stunned by the trace gif in the readme. I compiled the project and I can't seem to figure out how to generate one of those gifs, do you know how I could do so?

**Comment by Wunkolo** [comment]
This is the script I used to generate the the main gifs!
https://github.com/Wunkolo/qHilbert/blob/master/scripts/Hilbert.py

If you mean the red ones, that uses a modification where I just map the Hilbert curve index to the intensity in the red channel and offset it(with a modulo I believe)
https://github.com/Wunkolo/qHilbert/commits/master/scripts/Hilbert.py
I think one of these revisions are the one you are looking for. It's been quite some time 😅

**Comment by thrailkillr** [comment]
> This is the script I used to generate the the main gifs! https://github.com/Wunkolo/qHilbert/blob/master/scripts/Hilbert.py
> 
> If you mean the red ones, that uses a modification where I just map the Hilbert curve index to the intensity in the red channel and offset it(with a modulo I believe) https://github.com/Wunkolo/qHilbert/commits/master/scripts/Hilbert.py I think one of these revisions are the one you are looking for. It's been quite some time 😅

Thank you! I was originally looking for the code to generate the "HilbertRed-Trace.gif" but the older revisions seems to produce a nice looking colorful curve too. Have a nice day!

**Comment by Wunkolo** [comment]
For sure! I wrote some code here that does a similar technique to that gif that you may reference from as well!
https://www.shadertoy.com/view/XtGBDW
